import java.io.File;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String[] args) {
//		FunctionalController fnc = new FunctionalController();
//		fnc.uploadFunctionalReportJson("appid", "projectId", "testscenarioname", "runId", null);
		final File jsonFile = new File("appid" + File.separator + "projectId" + File.separator + "runId" + File.separator + "testscenarioname" + ".json");
		System.out.println(jsonFile.getAbsolutePath());
		final File dir = new File(jsonFile.getParent());
		System.out.println(dir.getAbsolutePath());
		System.out.println("we are done here--");
	}
}
